seed: 42
project_name: "MMVTO_Data_Preprocessing"
run_name: "initial_run"

data:
  train_data_dir: "./data/train"
  val_data_dir: "./data/val"
  batch_size: 32
  num_workers: 4

segmentation:
  model_type: "deeplabv3_resnet101"
  pretrained: true

pose_estimation:
  model_type: "hrnet_w48"
  pretrained: true

inpainting:
  model_type: "unet"
  in_channels: 3
  out_channels: 3

preprocessing:
  output_dir: "./data/processed"